language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
- sudo apt update
- sudo apt install -y libdbus-1-dev libxcb-shape0-dev libxcb-render0-dev libxcb-xfixes0-dev
script:
- cargo build
- cargo test
